services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: challenger
    ports:
      - '3000:3000'
    volumes:
      - ./:/node/app/
      - /node/app/node_modules
    command: sh -c "yarn start:dev"
